### ISSUE TITLE
Umbrella: Unit test and refactor

### ISSUE THREAD

**Issue by ElliotAOram** [neutrons/mantid_total_scattering#4]
In order to clean up and test the main script we should refactor out logical units of the code base. When refactoring these we should add unit tests to check the functionality is still correct and be sure to run the system tests to validate nothing has broken in the general workflow. Once the following sections have been refactored and tested we can move the main script into a class (one step closer to a Mantid algorithm). The main sections are: 
* [x] Loading (PR #3) 
* [x] Saving (Issue #9, PR #24)
* [ ] Vanadium Preparation (Step 2.0)
* [ ] Vanadium Normalisation (Step 2.1)
* [ ] Shapes and Geometry
Once these are done we should have a review of what is remaining and where to go next.
